src/Dental_Care/Models/Patient.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Dental_Care.Models
{
    public class Patient
    {
        /// <summary>
        /// Gets or sets the patient identifier.
        /// </summary>
        /// <value>
        /// The patient identifier.
        /// </value>
        public int PatientId { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>
        /// The name.
        /// </value>
        [Required(ErrorMessage = "Unesite ime pacijenta")]
        [Display(Name = "Ime")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or sets the last name.
        /// </summary>
        /// <value>
        /// The last name.
        /// </value>
        [Required(ErrorMessage = "Unesite prezime pacijenta")]
        [Display(Name = "Prezime")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or sets the date of birth.
        /// </summary>
        /// <value>
        /// The date of birth.
        /// </value>
        [Required(ErrorMessage = "Unesite datum rođenja pacijeta")]
        [Display(Name = "Datum rođenja")]
        public DateTime DateOfBirth { get; set; }

        /// <summary>
        /// Gets or sets the gender.
        /// </summary>
        /// <value>
        /// The gender.
        /// </value>
        [Required(ErrorMessage = "Odaberite pol pacijeta")]
        [Display(Name = "Pol")]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or sets the phone number.
        /// </summary>
        /// <value>
        /// The phone number.
        /// </value>
        [Required(ErrorMessage = "Unesite broj telefona pacijeta")]
        [StringLength(11, MinimumLength = 10, ErrorMessage ="Min broj karaktera je 10, max 11 ")]
        [Display(Name = "Broj telefona")]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or sets the email.
        /// </summary>
        /// <value>
        /// The email.
        /// </value>
        [Required(ErrorMessage = "Unesite email pacijeta")]
        [EmailAddressAttribute(ErrorMessage = "Unesite pravilan format email-a")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or sets the date of account creation.
        /// </summary>
        /// <value>
        /// The date of account creation.
        /// </value>
        public DateTime DateOfCreation { get; set; }

        /// <summary>
        /// Gets or sets the number of cardboard.
        /// </summary>
        /// <value>
        /// The number of cardboard.
        /// </value>
        [Required(ErrorMessage = "Unesite broj kartona")]
        [Display(Name = "Broj kartona")]
        public string NumberOfCardboard { get; set; }
    }
}

src/Dental_Care/Controllers/PatientsController.cs
using Dental_Care.Data.Entities;
using Dental_Care.Data.Repository;
using Dental_Care.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

/// <summary>
/// PatientsController
/// </summary>
namespace Dental_Care.Controllers
{
    public class PatientsController : Controller
    {
        /// <summary>
        /// The repository<PatientEntity>
        /// </summary>
        private readonly IRepository<PatientEntity> repository;

        /// <summary>
        /// Initializes a new instance of the <see cref="PatientsController"/> class.
        /// </summary>
        /// <param name="repository">The repository.</param>
        public PatientsController(IRepository<PatientEntity> repository)
        {
            this.repository = repository;
        }

        /// <summary>
        /// Returns the list of existing patients.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            string g = "";
            List<PatientEntity> patientsEntity = repository.GetAll();
            List<Patient> patientsModel = new List<Patient>();
            foreach (PatientEntity pEntity in patientsEntity)
            {
                if (pEntity.Gender == "M")
                {
                    g = "Muški";
                }
                else if (pEntity.Gender == "F")
                {
                    g = "Ženski";
                }
                Patient pModel = new Patient()
                {
                    PatientId = pEntity.Id,
                    FirstName = pEntity.FirstName,
                    LastName = pEntity.LastName,
                    DateOfBirth = pEntity.DateOfBirth,
                    Gender = g,
                    Phone = pEntity.Phone,
                    Email = pEntity.Email,
                    NumberOfCardboard = pEntity.NumberOfCardboard,
                    DateOfCreation = pEntity.DateOfCreation
                };
                patientsModel.Add(pModel);
            }

            return View(patientsModel);
        }

        /// <summary>
        /// Detailses the specified patient.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            PatientEntity pEntitySpecific = repository.GetById(id);
            if (pEntitySpecific.Gender == "M")
            {
                ViewBag.Gender = "Muški";
            }
            else if (pEntitySpecific.Gender == "F")
            {
                ViewBag.Gender = "Ženski";
            }
            return View(pEntitySpecific);
        }

        /// <summary>
        /// Creates a new instance of the patient.
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates a new instance of the patient.
        /// </summary>
        /// <param name="pModel">The p model.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Patient pModel)
        {
            if (ModelState.IsValid)
            {
                PatientEntity pEntity = new PatientEntity()
                {
                    Id = pModel.PatientId,
                    FirstName = pModel.FirstName,
                    LastName = pModel.LastName,
                    DateOfBirth = pModel.DateOfBirth,
                    Gender = pModel.Gender,
                    Phone = pModel.Phone,
                    Email = pModel.Email,
                    NumberOfCardboard = pModel.NumberOfCardboard,
                    DateOfCreation = pModel.DateOfCreation
                };

                repository.Create(pEntity);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        /// <summary>
        /// Edits the specified patient.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            PatientEntity pEntitySpecific = repository.GetById(id);

            if (pEntitySpecific == null)
            {
                return NotFound();
            }

            Patient pModel = new Patient()
            {
                PatientId = pEntitySpecific.Id,
                FirstName = pEntitySpecific.FirstName,
                LastName = pEntitySpecific.LastName,
                DateOfBirth = pEntitySpecific.DateOfBirth,
                Gender = pEntitySpecific.Gender,
                Phone = pEntitySpecific.Phone,
                Email = pEntitySpecific.Email,
                NumberOfCardboard = pEntitySpecific.NumberOfCardboard,
                DateOfCreation = pEntitySpecific.DateOfCreation
            };

            return View(pModel);
        }

        /// <summary>
        /// Edits the specified patient.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="pModel">The p model.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Patient pModel)
        {
            PatientEntity pEntitySpecific = repository.GetById(id);
            try
            {
                pEntitySpecific.FirstName = pModel.FirstName;
                pEntitySpecific.LastName = pModel.LastName;
                pEntitySpecific.DateOfBirth = pModel.DateOfBirth;
                pEntitySpecific.Gender = pModel.Gender;
                pEntitySpecific.Phone = pModel.Phone;
                pEntitySpecific.Email = pModel.Email;
                pEntitySpecific.NumberOfCardboard = pModel.NumberOfCardboard;

                repository.Edit(id, pEntitySpecific);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Deletes the specified patient.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            PatientEntity pEntitySpecific = repository.GetById(id);
            if (pEntitySpecific.Gender == "M")
            {
                ViewBag.Gender = "Muški";
            }
            else if (pEntitySpecific.Gender == "F")
            {
                ViewBag.Gender = "Ženski";
            }
            return View(pEntitySpecific);
        }

        /// <summary>
        /// Deletes the specified patient.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="collection">The collection.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, PatientEntity pEntity)
        {
            try
            {
                PatientEntity pEntitySpecific = repository.GetById(id);
                repository.Delete(pEntitySpecific);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Dental_Care/Views/Patients/Create.cshtml
@model Patient

@{
    ViewData["Title"] = "Novi pacijent";
}

<h2>Dodajte novog pacijenta</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Patients" asp-action="Create" method="post" onsubmit="Validation()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input type="text" asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input type="text" asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input type="date" asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label><br />
                <select asp-for="Gender" required class="form-control">
                    <option value="M">Muški</option>
                    <option value="F">Ženski</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input type="tel" asp-for="Phone" class="form-control" placeholder="065/123456" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfCardboard" class="control-label"></label>
                <input type="text" asp-for="NumberOfCardboard" class="form-control" />
                <span asp-validation-for="NumberOfCardboard" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="DateOfCreation" class="control-label"></label>
                <input type="datetime" asp-for="DateOfCreation" class="form-control" value="@DateTime.Today" />
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Patients" asp-action="Index">Povratak na listu pacijenata</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Dental_Care/Views/Patients/Delete.cshtml
@model Dental_Care.Data.Entities.PatientEntity
@{
    ViewData["Title"] = "Biranje podataka";
}

<h3>Da li ste sigurni da želite da obrišete pacijenta?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ime
        </dt>
        <dd>
            @Model.FirstName
        </dd>
        <dt>
            Prezime
        </dt>
        <dd>
            @Model.LastName
        </dd>
        <dt>
            Datum rođenja
        </dt>
        <dd>
            @Model.DateOfBirth.ToShortDateString()
        </dd>
        <dt>
            Pol
        </dt>
        <dd>
            @ViewBag.Gender
        </dd>
        <dt>
            Telefon
        </dt>
        <dd>
            @Model.Phone
        </dd>
        <dt>
            email
        </dt>
        <dd>
            @Model.Email
        </dd>
        <dt>
            broj kartona
        </dt>
        <dd>
            @Model.NumberOfCardboard
        </dd>
        <dt>
            Datum otvaranja kartona
        </dt>
        <dd>
            @Model.DateOfCreation.ToShortDateString()
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Obriši" class="btn btn-default" /> |
        <a asp-action="Index">Povratak na listu pacijenata</a>
    </form>
</div>

src/Dental_Care/Views/Patients/Details.cshtml
@model Dental_Care.Data.Entities.PatientEntity
@{
    ViewData["Title"] = "Detalji";
}
<h2>Detalji o pacijentu</h2>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Ime
        </dt>
        <dd>
            @Model.FirstName
        </dd>
        <dt>
            Prezime
        </dt>
        <dd>
            @Model.LastName
        </dd>
        <dt>
            Datum rođenja
        </dt>
        <dd>
            @Model.DateOfBirth.ToShortDateString()
        </dd>
        <dt>
            Pol
        </dt>
        <dd>
            @ViewBag.Gender
        </dd>
        <dt>
            Telefon
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            email
        </dt>
        <dd>
            @Model.Email
        </dd>
        <dt>
            broj kartona
        </dt>
        <dd>
            @Model.NumberOfCardboard
        </dd>
        <dt>
            Datum otvaranja kartona
        </dt>
        <dd>
            @Model.DateOfCreation.ToShortDateString()
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Promeni</a> |
    <a asp-action="Index">Povratak na listu pacijenata</a>
</div>

src/Dental_Care/Views/Patients/Edit.cshtml
@model Patient

@{
    ViewData["Title"] = "Promena podataka o pacijentu";
}

<h2>Promenite podatke o pacijentu</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Patients" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="PatientId" class="control-label"></label>
                <input type="number" asp-for="PatientId" class="form-control" />
                <span asp-validation-for="PatientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input type="text" asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input type="text" asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input type="date" asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label><br />
                <select id="select1" asp-for="Gender" required class="form-control">
                    <option id="s1" value="M">Muški</option>
                    <option id="s2" value="F">Ženski</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input type="text" asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfCardboard" class="control-label"></label>
                <input type="text" asp-for="NumberOfCardboard" class="form-control" />
                <span asp-validation-for="NumberOfCardboard" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="DateOfCreation" class="control-label"></label>
                <input type="date" asp-for="DateOfCreation" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Patients" asp-action="Index">Povratak na listu pacijenata</a>
</div>

<script>
    var sM = $("#s1");
    var sF = $("#s2");

    $().ready(function () {

        if (@Model.Gender=="M") {
            s1.attr("selected", "selected");
        }
        else if (@Model.Gender=="F") {
            s2.attr("selected", "selected");
        }
        else {
            s1.attr("selected", "selected");
             }
    });
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Dental_Care/Views/Patients/Index.cshtml
@model IEnumerable<Dental_Care.Models.Patient>
@{
    ViewData["Title"] = "Lista pacijenata";
}
<p>
    <a asp-action="Create">Dodajte novog pacijenta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Ime
            </th>
            <th>
                Prezime
            </th>
            <th>
                Datum rođenja
            </th>
            <th>
                Pol
            </th>
            <th>
                Broj telefona
            </th>
            <th>
                Email
            </th>
            <th>
                Broj kartona
            </th>
            <th>
                Datum otvaranja kartona
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.DateOfBirth.ToShortDateString()
                </td>
                <td>
                    @item.Gender
                </td>
                <td>
                    @item.Phone
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @item.NumberOfCardboard
                </td>
                <td>
                    @item.DateOfCreation.ToShortDateString()
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.PatientId">Promeni</a> |
                    <a asp-action="Details" asp-route-id="@item.PatientId">Detalji</a> |
                    <a asp-action="Delete" asp-route-id="@item.PatientId">Obriši</a>
                </td>
            </tr>
        }
    </tbody>
</table>