src/Dental_Care/Models/Exam.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Dental_Care.Models
{
    /// <summary>
    /// Exam
    /// </summary>
    public class Exam
    {
        /// <summary>
        /// Gets or sets the exam identifier.
        /// </summary>
        /// <value>
        /// The exam identifier.
        /// </value>
        public int ExamId { get; set; }

        /// <summary>
        /// Gets or sets the date of exam.
        /// </summary>
        /// <value>
        /// The date of exam.
        /// </value>
        [Required(ErrorMessage = "Unesite datum pregleda")]
        [Display(Name = "Datum pregleda")]
        public DateTime DateOfExam { get; set; }

        /// <summary>
        /// Gets or sets the patient identifier.
        /// </summary>
        /// <value>
        /// The patient identifier.
        /// </value>
        [Required(ErrorMessage = "Unesite id pacijenta")]
        [Display(Name = "Id pacijenta")]
        public int PatientId { get; set; }

        public string Name { get; set; }
    }
}

src/Dental_Care/Controllers/ExamsController.cs
using Dental_Care.Data.Entities;
using Dental_Care.Data.Repository;
using Dental_Care.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

/// <summary>
/// ExamsController
/// </summary>
namespace Dental_Care.Controllers
{
    public class ExamsController : Controller
    {
        /// <summary>
        /// The repository
        /// </summary>
        private readonly IRepository<ExamEntity> repository;

        /// <summary>
        /// The repository patients
        /// </summary>
        private readonly PatientRepository repositoryPatients;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExamsController"/> class.
        /// </summary>
        /// <param name="repository">The repository.</param>
        public ExamsController(IRepository<ExamEntity> repository,
            PatientRepository repositoryPatients)
        {
            this.repository = repository;
            this.repositoryPatients = repositoryPatients;
        }

        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            //IEnumerable<PatientEntity> patientsEntity = repositoryPatients.GetAll();
            List<ExamEntity> examEntities = repository.GetAll();
            if (examEntities == null)
            {
                return View();
            }
            List<Exam> examsModel = new List<Exam>();
            foreach (ExamEntity eEntity in examEntities)
            {
                Exam eModel = new Exam()
                {
                    ExamId = eEntity.Id,
                    DateOfExam = eEntity.DateOfExam,
                    PatientId = eEntity.PatientId,
                    Name = repositoryPatients.GetPatientName(eEntity.PatientId)
                };
                examsModel.Add(eModel);
            }

            return View(examsModel);
        }

        /// <summary>
        /// Detailses the specified exam.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public IActionResult Details(int id)
        {
            ExamEntity eEntity = repository.GetById(id);
            if (eEntity == null)
            {
                return NotFound();
            }
            Exam eModel = new Exam()
            {
                ExamId = eEntity.Id,
                DateOfExam = eEntity.DateOfExam,
                PatientId = eEntity.PatientId,
                Name = repositoryPatients.GetPatientName(eEntity.PatientId)
            };
            return View(eModel);
        }

        /// <summary>
        /// Creates exam instance.
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            IEnumerable<PatientEntity> patientsEntity = repositoryPatients.GetAll();
            ViewBag.Poruka = null;
            if (patientsEntity == null)
            {
                ViewBag.Poruka = "Prvo morate dodati pacijenta pa onda mu dodeliti pregled";
                return View();
            }
            List<SelectListItem> names = new List<SelectListItem>();
            foreach (var p in patientsEntity)
            {
                string id = p.Id.ToString();
                SelectListItem sl = new SelectListItem()
                {
                    Value = id,
                    Text = $"{p.FirstName} {p.LastName}"
                };

                names.Add(sl);
            }
            ViewBag.Names = names;
            return View();
        }

        /// <summary>
        /// Creates the specified exam.
        /// </summary>
        /// <param name="eModel">The e model.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Exam eModel)
        {
            int id = eModel.PatientId;
            PatientEntity pEntitySpecific = repositoryPatients.GetById(id);

            ViewBag.Poruka = null;

            if (pEntitySpecific == null)
            {
                ViewBag.Poruka = "Pacijent ne postoji pod izabranim id";
                return View();
            }
            if (ModelState.IsValid)
            {
                ExamEntity eEntity = new ExamEntity()
                {
                    Id = eModel.ExamId,
                    DateOfExam = eModel.DateOfExam,
                    PatientId = eModel.PatientId
                };
                repository.Create(eEntity);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        /// <summary>
        /// Edits the specified exam.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Edit(int id)
        {
            ExamEntity eEntitySpecific = repository.GetById(id);

            if (eEntitySpecific == null)
            {
                return NotFound();
            }
            IEnumerable<PatientEntity> patientsEntity = repositoryPatients.GetAll();
            //ViewBag.Poruka = null;
            //if (patientsEntity == null)
            //{
            //    ViewBag.Poruka = "Nije pronađen pacijent";
            //    return View();
            //}
            List<SelectListItem> names = new List<SelectListItem>();
            foreach (var p in patientsEntity)
            {
                string idP = p.Id.ToString();
                SelectListItem sl = new SelectListItem()
                {
                    Value = idP,
                    Text = $"{p.FirstName} {p.LastName}"
                };

                names.Add(sl);
            }
            ViewBag.Names = names;

            Exam eModel = new Exam()
            {
                ExamId = eEntitySpecific.Id,
                DateOfExam = eEntitySpecific.DateOfExam,
                PatientId = eEntitySpecific.PatientId
            };
            return View(eModel);
        }

        /// <summary>
        /// Edits the specified exam.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="eModel">The e model.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Exam eModel)
        {
            ExamEntity eEntitySpecific = repository.GetById(id);
            try
            {
                eEntitySpecific.PatientId = eModel.PatientId;
                eEntitySpecific.DateOfExam = eModel.DateOfExam;
                repository.Edit(id, eEntitySpecific);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Deletes the specified exam.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            ExamEntity eEntity = repository.GetById(id);
            if (eEntity == null)
            {
                return NotFound();
            }
            Exam eModel = new Exam()
            {
                ExamId = eEntity.Id,
                DateOfExam = eEntity.DateOfExam,
                PatientId = eEntity.PatientId,
                Name = repositoryPatients.GetPatientName(eEntity.PatientId)
            };
            return View(eModel);
        }

        /// <summary>
        /// Deletes the specified exam.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="collection">The collection.</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Exam eModel)
        {
            try
            {
                ExamEntity eEntity = repository.GetById(id);
                repository.Delete(eEntity);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

src/Dental_Care/Views/Exams/Create.cshtml
@model Dental_Care.Models.Exam
@{
    ViewData["Title"] = "Dodajte novi pregled";
}
@{
    if (ViewBag.Poruka == null)
    {
        <h2>Dodajte novi pregled</h2>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label class="control-label">Ime i prezime pacijenta</label>
                        <select asp-for="PatientId" asp-items="@ViewBag.Names" class="form-control"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfExam" class="control-label"></label>
                        <input type="datetime-local" asp-for="DateOfExam" class="form-control" />
                        <span asp-validation-for="DateOfExam" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Sačuvaj" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Povratak na spisak pregleda</a>
        </div>
    }
    else
    {
        <h2>@ViewBag.Poruka</h2>

        <div>
            <a asp-action="Create">Povratak na unos novog pregleda</a>
        </div>
        <div>
            <a asp-action="Index">Povratak na spisak pregleda</a>
        </div>
    }
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/Dental_Care/Views/Exams/Delete.cshtml
@model Dental_Care.Models.Exam
@{
    ViewData["Title"] = "Brisanje";
}

<h3>Da li ste sigurni da želite da obrišete pregled?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id pregleda
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>
        <dt>
            Datum pregleda
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfExam)
        </dd>
        <dt>
            Id pacijenta
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt>
            Ime i prezime pacijenta
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Obriši" class="btn btn-default" /> |
        <a asp-action="Index">Povratak na listu pregleda</a>
    </form>
</div>

src/Dental_Care/Views/Exams/Details.cshtml
@model Dental_Care.Models.Exam

@{
    ViewData["Title"] = "Detalji o pregledu";
}

<h2>Detalji o pregledu</h2>

<div>  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Id pregleda
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ExamId)
        </dd>
        <dt>
            Datum pregleda
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfExam)
        </dd>
        <dt>
            Id pacijenta
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PatientId)
        </dd>
        <dt>
            Ime i prezime pacijenta
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ExamId">Promeni</a> |
    <a asp-action="Index">Povratak na listu pregleda</a>
</div>

src/Dental_Care/Views/Exams/Edit.cshtml
@model Exam
@{
    ViewData["Title"] = "Promeni pregled";
}
<h2>Promenite podatke o pregledu</h2>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Exams" asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="ExamId" class="control-label"></label>
                <input type="number" asp-for="ExamId" class="form-control" />
                <span asp-validation-for="ExamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Ime i prezime pacijenta</label>
                <select asp-for="PatientId" asp-items="@ViewBag.Names" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="DateOfExam" class="control-label"></label>
                <input type="datetime-local" asp-for="DateOfExam" class="form-control" />
                <span asp-validation-for="DateOfExam" class="text-danger"></span>
            </div>         
            <div class="form-group">
                <input type="submit" value="Sačuvaj" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-controller="Exams" asp-action="Index">Povratak na listu pregleda</a>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/Dental_Care/Views/Exams/Index.cshtml
@using Dental_Care.Controllers
@model IEnumerable<Dental_Care.Models.Exam>

@{
    ViewData["Title"] = "Pregledi";
}

<h2>Spisak svih pregleda</h2>

<p>
    <a asp-action="Create">Dodajte novi pregled</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    Broj pregleda
                </th>
                <th>
                    Pacijent
                </th>
                <th>
                    Datum i vreme pregleda
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ExamId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfExam)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ExamId">Promeni</a> |
                <a asp-action="Delete" asp-route-id="@item.ExamId">Obriši</a> |
                <a asp-action="Details" asp-route-id="@item.ExamId">Detalji</a>
            </td>
        </tr>
}
    </tbody>
</table>